/**
 * Fixture generator — creates a minimal valid React app zip.
 *
 * Generates: index.html, package.json (with two dependencies), README.md
 *
 * Run standalone:  npx ts-node tests/fixtures/generate-zip.ts
 * Or imported:     import { generateFixture } from './generate-zip';
 *
 * The zip is always freshly generated so it is never stale.
 */

import JSZip from 'jszip';
import * as fs from 'node:fs';
import * as path from 'node:path';

const OUT_PATH = path.join(__dirname, 'sample-app.zip');

export async function generateFixture(outPath = OUT_PATH): Promise<string> {
  const zip = new JSZip();

  zip.file(
    'index.html',
    `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sample VibeMesh App</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="./main.jsx"></script>
  </body>
</html>
`,
  );

  zip.file(
    'package.json',
    JSON.stringify(
      {
        name: 'sample-vibemesh-app',
        version: '1.0.0',
        description: 'A minimal React app for testing VibeMesh uploads.',
        main: 'index.html',
        dependencies: {
          react: '^18.3.1',
          'react-dom': '^18.3.1',
        },
        scripts: {
          dev: 'vite',
          build: 'vite build',
        },
      },
      null,
      2,
    ),
  );

  zip.file(
    'README.md',
    `# Sample VibeMesh App

A minimal React scaffold generated by the VibeMesh test fixture generator.

## Setup

\`\`\`bash
npm install
npm run dev
\`\`\`

## What's inside

| File | Purpose |
|------|---------|
| \`index.html\` | Entry point |
| \`package.json\` | Packages manifest |
`,
  );

  const buffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, buffer);

  return outPath;
}

// Allow running this file directly: `npx ts-node tests/fixtures/generate-zip.ts`
if (require.main === module) {
  generateFixture()
    .then((p) => console.log(`Fixture written to ${p}`))
    .catch((err) => {
      console.error(err);
      process.exit(1);
    });
}
